spring.main.web-application-type=none
spring.main.banner-mode=off

# Mode: generate-codes | generate-pdf
app.mode=generate-pdf

# Code generation properties
app.event-code=DEMO
app.code-count=50

# PDF generation properties
app.input-path=codes.csv
app.output-path=qr-codes.pdf
app.base-url=https://my.site/gallery/
app.qr-size=200
app.grid-columns=3
app.grid-rows=4
app.show-cutting-lines=false
app.event-name=
